# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker \
    dagster-gcp

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster-docker.yaml workspace-docker.yaml $DAGSTER_HOME

RUN mv $DAGSTER_HOME/dagster-docker.yaml $DAGSTER_HOME/dagster.yaml && \
    mv $DAGSTER_HOME/workspace-docker.yaml $DAGSTER_HOME/workspace.yaml


COPY key.json /opt/dagster/dagster_home/key.json

ENV GOOGLE_APPLICATION_CREDENTIALS=/opt/dagster/dagster_home/key.json

# Configure TLS settings for older SQL Server versions
RUN sed -i 's/^MinProtocol\s*=.*$/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf && \
    sed -i 's/^CipherString\s*=.*$/CipherString = DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf


WORKDIR $DAGSTER_HOME